"""
本代码实现了 PoseCNN 网络架构，采用 PyTorch 深度学习框架进行构建。
"""
import torch
import torch.nn as nn
from torch.nn.init import kaiming_normal_
import torchvision.models as models
from torchvision.ops import RoIPool

import numpy as np
import random
import statistics
import time
from typing import Dict, List, Callable, Optional

from utils import quaternion_to_matrix
from p3_helper import HoughVoting, _LABEL2MASK_THRESHOL, loss_cross_entropy, loss_Rotation, IOUselection


def hello_pose_cnn():
    """
    这是一个示例函数，我们将尝试导入并执行它，以验证我们的环境在 Google Colab 上配置正确。
    """
    print("Hello from pose_cnn.py!")


class FeatureExtraction(nn.Module):
    """
    PoseCNN 的特征嵌入模块。使用预训练的 VGG16 网络作为骨干网络（backbone）。
    """    
    def __init__(self, pretrained_model):
        super(FeatureExtraction, self).__init__()
        embedding_layers = list(pretrained_model.features)[:30]
        # 从网络的开始到第一个输出特征图的嵌入模块
        self.embedding1 = nn.Sequential(*embedding_layers[:23])
        # 从第一个输出特征图到第二个输出特征图的嵌入模块
        self.embedding2 = nn.Sequential(*embedding_layers[23:])

        # 冻结特定层的权重，使其在训练过程中不更新
        for i in [0, 2, 5, 7, 10, 12, 14]:
            self.embedding1[i].weight.requires_grad = False
            self.embedding1[i].bias.requires_grad = False
    
    def forward(self, datadict):
        """
        输入数据的处理过程：
        feature1: [bs, 512, H/8, W/8]  # 第一个特征图，尺寸为原始图像的1/8
        feature2: [bs, 512, H/16, W/16]  # 第二个特征图，尺寸为原始图像的1/16
        """ 
        feature1 = self.embedding1(datadict['rgb'])
        feature2 = self.embedding2(feature1)
        # 返回两个特征图
        return feature1, feature2

class SegmentationBranch(nn.Module):
    """
    实例分割模块 
    """    
    def __init__(self, num_classes = 10, hidden_layer_dim = 64):
        super(SegmentationBranch, self).__init__()

        ######################################################################
        # TODO: Initialize instance segmentation branch layers for PoseCNN.  #
        #                                                                    #
        # 1) Both feature1 and feature2 should be passed through a 1x1 conv  #
        # + ReLU layer (seperate layer for each feature).                    #
        #                                                                    #
        # 2) Next, intermediate features from feature1 should be upsampled   #
        # to match spatial resolution of features2.                          #
        #                                                                    #
        # 3) Intermediate features should be added, element-wise.            #
        #                                                                    #
        # 4) Final probability map generated by 1x1 conv+ReLU -> softmax     #
        #                                                                    #
        # It is recommended that you initialize each convolution kernel with #
        # the kaiming_normal initializer and each bias vector to zeros.      #
        #                                                                    #
        # Note: num_classes passed as input does not include the background  #
        # our desired probability map should be over classses and background #
        # Input channels will be 512, hidden_layer_dim gives channels for    #
        # each embedding layer in this network.                              #
        ######################################################################
        self.num_classes = num_classes


        #TODO 1: 在这里你需要传入输入通道数、输出通道数和卷积核大小，完成卷积层和ReLU层的初始化
        self.conv1 = nn.Conv2d(    )

        nn.init.kaiming_normal_(self.conv1.weight)
        nn.init.zeros_(self.conv1.bias)
        self.relu1 = nn.ReLU()


        self.conv2 = nn.Conv2d(    )

        nn.init.kaiming_normal_(self.conv2.weight)
        nn.init.zeros_(self.conv2.bias)
        self.relu2 = nn.ReLU()

        # TODO 2: 在这里你需要完成最后一个卷积层的初始化，self.conv3 是最终的卷积层，负责将经过前两层的特征图映射到最终类别数 + 背景类别的数量
        self.conv3 = nn.Conv2d(    )

        nn.init.kaiming_normal_(self.conv3.weight)
        nn.init.zeros_(self.conv3.bias)
        self.relu3 = nn.ReLU()


        # TODO 3: 在这里你需要定义 softmax 层，确保每个像素点的类别概率和为 1
        self.softmax =
        ######################################################################
        #                            END OF YOUR CODE                        #
        ######################################################################


    def forward(self, feature1, feature2):
        """
        参数说明：
            feature1：来自特征提取网络的第一层特征图，尺寸为 (B, 512, h, w)，
                    其中 B 表示批次大小，512 表示特征图的通道数，h 和 w 分别是特征图的高度和宽度。
            feature2：来自特征提取网络的第二层特征图，尺寸为 (B, 512, h//2, w//2)，
                    这是对 feature1 进行下采样后的结果，尺寸通常是 feature1 的一半。

        返回值：
            probability：每个像素点的分类概率图，表示该像素属于各个类别的概率。
                        输出的尺寸为 (B, num_classes+1, H, W)，其中 num_classes+1 包括所有类别（包括背景类别）。
            segmentation：每个像素点的预测类别 ID，表示概率最高的类别。
                        输出的尺寸为 (B, H, W)，每个像素点的值是类别的 ID。
            bbx：通过预测的分割结果提取的边界框。边界框的提取可以通过调用 `self.label2bbx(segmentation)` 实现。
                输出的尺寸为 (N, 6)，每个边界框包含以下信息：
                (batch_ids, x1, y1, x2, y2, cls)，其中 N 是检测到的边界框的数量。
        """
        probability = None
        segmentation = None
        bbx = None
        
        ######################################################################
        # TODO: Implement forward pass of instance segmentation branch.      #
        ######################################################################
        
        #TODO 4 在这里，你需要填充代码来执行卷积操作并进行 ReLU 激活
        x1 =  
        x2 =  
        temp = nn.functional.interpolate(x2, scale_factor=2) + x1

        #TODO 5 这里你需要对中间结果 `temp` 进行进一步的上采样，确保最终的特征图尺寸为 (480, 640)
        up_sample = nn.functional.interpolate(   )  # up_sample = (N, 64, 480, 640)

        x3 = self.conv3(up_sample)  # x3 = (N, 11, 480, 640)


        probability = self.softmax(x3)
        segmentation = torch.argmax(probability, dim=1)  # (B, H, W)
        bbx = self.label2bbx(segmentation)

        ######################################################################
        #                            END OF YOUR CODE                        #
        ######################################################################

        return probability, segmentation, bbx
    
    def label2bbx(self, label):
        bbx = []  # 用于存储边界框
        bs, H, W = label.shape  # 获取标签尺寸
        device = label.device  # 获取标签所在设备

        # 扩展标签并与类别目标进行比较
        label_repeat = label.view(bs, 1, H, W).repeat(1, self.num_classes, 1, 1).to(device)
        label_target = torch.linspace(0, self.num_classes - 1, steps=self.num_classes).view(1, -1, 1, 1).repeat(bs, 1, H, W).to(device)
        mask = (label_repeat == label_target)

        # 遍历批次和类别，提取非背景类别的边界框
        for batch_id in range(mask.shape[0]):
            for cls_id in range(mask.shape[1]):
                if cls_id != 0:  # 排除背景
                    y, x = torch.where(mask[batch_id, cls_id] != 0)
                    if y.numel() >= _LABEL2MASK_THRESHOL:  # 判断类别是否足够
                        bbx.append([batch_id, torch.min(x).item(), torch.min(y).item(), 
                                    torch.max(x).item(), torch.max(y).item(), cls_id])

        # 将边界框转换为张量并返回
        bbx = torch.tensor(bbx).to(device)
        return bbx

        
class TranslationBranch(nn.Module):
    """
    3D Translation Estimation Module for PoseCNN. 
    """    
    def __init__(self, num_classes = 10, hidden_layer_dim = 128):
        super(TranslationBranch, self).__init__()
        
        ######################################################################
        # TODO: Initialize layers of translation branch for PoseCNN.         #
        # It is recommended that you initialize each convolution kernel with #
        # the kaiming_normal initializer and each bias vector to zeros.      #
        ######################################################################
        
        self.num_classes = num_classes
        
        #TODO 6 完成卷积层 conv1 conv2 的初始化
        # 1) `conv1` 和 `conv2` 需要处理输入特征，并将其转换为 `hidden_layer_dim` 个输出通道。
        # 2) `conv3` 用于生成最终的 3D 平移预测，它的输出通道数是 `3 + num_classes`。
        # 3) 请使用 Kaiming 正态分布对卷积核进行初始化，并将偏置初始化为零。

        self.conv1 = 
        nn.init.kaiming_normal_(self.conv1.weight)
        nn.init.zeros_(self.conv1.bias)
        self.relu1 = 


        self.conv2 = 
        nn.init.kaiming_normal_(self.conv2.weight)
        nn.init.zeros_(self.conv2.bias)
        self.relu2 = 


        self.conv3 = 
        nn.init.kaiming_normal_(self.conv3.weight)
        nn.init.zeros_(self.conv3.bias)

        ######################################################################
        #                            END OF YOUR CODE                        #
        ######################################################################

    def forward(self, feature1, feature2):
        """
        feature1 和 feature2：是从网络的特征提取部分（例如 VGG16）获取的特征图。feature1 的尺寸是 (B, 512, h, w)，而 feature2 的尺寸是 (B, 512, h//2, w//2)，表示通过下采样得到的特征图。
        translation：是物体质心（中心点）的预测映射，它的尺寸为 (N, 3 * num_classes, H, W)，其中 N 是批次大小，num_classes 是类别数量，H 和 W 是特征图的高和宽。
        """
        translation = None
        ######################################################################
        # TODO: Implement forward pass of translation branch.                #
        ######################################################################
        # 在这里，你需要完成平移分支的前向传播：
        # 1) 你需要对 feature1 和 feature2 进行卷积操作，并应用 ReLU 激活函数
        # 2) 然后，你需要将 feature2 进行上采样，并与 feature1 进行相加
        # 3) 最后，你需要将相加后的特征图传递到卷积层，得到预测的平移信息。


        # TODO 7: 完成卷积层和 ReLU 操作，填充卷积 + ReLU 操作
        x1 =  
        x2 = 

        # TODO 8: 对 feature2 进行上采样，并与 feature1 进行逐元素加法
        temp = 

        x3 = self.conv3(temp)  # x3 = (N, 11, H, W)

        translation = nn.functional.interpolate(x3, size=(480, 640), mode='bilinear')  # temp = (N, 64, 480, 640)
        ######################################################################
        #                            END OF YOUR CODE                        #
        ######################################################################
        return translation

class RotationBranch(nn.Module):
    """
    3D Rotation Regression Module for PoseCNN. 
    """    
    def __init__(self, feature_dim = 512, roi_shape = 7, hidden_dim = 4096, num_classes = 10):
        super(RotationBranch, self).__init__()

        ######################################################################
        # TODO: Initialize layers of rotation branch for PoseCNN.            #
        # It is recommended that you initialize each convolution kernel with #
        # the kaiming_normal initializer and each bias vector to zeros.      #
        ######################################################################
        # 在这里，你需要完成旋转分支的初始化：
        # 1) `roi_shape`，`num_classes` 和 `feature_dim` 是由外部传入的参数，确保正确使用这些参数来初始化层。
        # 2) `roi1` 和 `roi2` 是 RoI 池化层，它们负责提取感兴趣区域的特征。你需要初始化这两个 RoI 池化层。
        # 3) `lin1` 和 `lin2` 是全连接层，它们负责将提取的特征映射到旋转角度的预测。你需要初始化这两个全连接层。
        self.roi_shape = roi_shape
        self.num_classes = num_classes
        self.feature_dim = feature_dim

        #TODO 9: 完成 RoI 池化层的初始化
        self.roi1 = RoIPool(  )
        self.roi2 = RoIPool(  )

        # TODO 10: 完成全连接层 lin1 的初始化
        self.lin1 = nn.Linear(  )
        nn.init.kaiming_normal_(self.lin1.weight)
        nn.init.zeros_(self.lin1.bias)
        self.relu_lin = nn.ReLU()

        # TODO 11: 完成全连接层 lin2 的初始化
        self.lin2 = nn.Linear(  )  
        nn.init.kaiming_normal_(self.lin2.weight)
        nn.init.zeros_(self.lin2.bias)
        ######################################################################
        #                            END OF YOUR CODE                        #
        ######################################################################


    def forward(self, feature1, feature2, bbx):
        """
        Args:
            feature1: Features from feature extraction backbone (B, 512, h, w)
            feature2: Features from feature extraction backbone (B, 512, h//2, w//2)
            bbx: Bounding boxes of regions of interst (N, 5) with (batch_ids, x1, y1, x2, y2)
        Returns:
            quaternion: Regressed components of a quaternion for each class at each ROI.
                quaternion size: (N,4*num_classes)
        """
        quaternion = None

        ######################################################################
        # TODO: Implement forward pass of rotation branch.                   #
        ######################################################################
        # 在这里，你需要完成旋转分支的前向传播：
        # TODO 12: 完成 RoI 池化层的前向传播
        out1 = self.roi1(    )
        out2 = self.roi2(    )
        out = out1 + out2

        # TODO 13: 使用全连接层进行旋转角度的预测
        quaternion = self.lin2(    )


        ######################################################################
        #                            END OF YOUR CODE                        #
        ######################################################################

        return quaternion

class PoseCNN(nn.Module):
    """
    PoseCNN
    """
    def __init__(self, pretrained_backbone, models_pcd, cam_intrinsic):
        super(PoseCNN, self).__init__()

        self.iou_threshold = 0.7
        self.models_pcd = models_pcd
        self.cam_intrinsic = cam_intrinsic

        ######################################################################
        # TODO: Initialize layers and components of PoseCNN.                 #
        #                                                                    #
        # Create an instance of FeatureExtraction, SegmentationBranch,       #
        # TranslationBranch, and RotationBranch for use in PoseCNN           #
        ######################################################################
        # 在这里，你需要初始化 PoseCNN 网络中的所有层：
        # 1) `FeatureExtraction` 是特征提取模块，需要使用 VGG16 作为骨干网络来初始化 `FeatureExtraction`。
        # 2) `SegmentationBranch` 用于实例分割，需要初始化该分支。
        # 3) `RotationBranch` 用于旋转角度的预测，需要初始化该分支。
        # 4) `TranslationBranch` 用于平移预测，需要初始化该分支


        # TODO 14: 在这里，你需要初始化每个分支
        vgg16 = models.vgg16(weights=models.VGG16_Weights.IMAGENET1K_V1)

        self.feature_extractor =  #填充 FeatureExtraction 初始化
        self.segmentation_branch =  #填充 SegmentationBranch 初始化
        self.RotationBranch =  #填充 RotationBranch 初始化
        self.TranslationBranch =  # 填充 TranslationBranch 初始化


        ######################################################################
        #                            END OF YOUR CODE                        #
        ######################################################################


    def forward(self, input_dict):
        """
        input_dict = {
            'rgb',
            'depth',
            'objs_id',
            'mask',
            'bbx',
            'RTs'
        }
        """


        if self.training:
            loss_dict = {
                "loss_segmentation": 0,
                "loss_centermap": 0,
                "loss_R": 0
            }

            gt_bbx = self.getGTbbx(input_dict)

            ######################################################################
            # TODO: Implement PoseCNN's forward pass for training.               #
            #                                                                    #
            # Model should extract features, segment the objects, identify roi   #
            # object bounding boxes, and predict rotation and translations for   #
            # each roi box.                                                      #
            #                                                                    #
            # The training loss for semantic segmentation should be stored in    #
            # loss_dict["loss_segmentation"] and calculated using the            #
            # loss_cross_entropy(.) function.                                    #
            #                                                                    #
            # The training loss for translation should be stored in              #
            # loss_dict["loss_centermap"] using the L1loss function.             #
            #                                                                    #
            # The training loss for rotation should be stored in                 #
            # loss_dict["loss_R"] using the given loss_Rotation function.        #
            ######################################################################
            # Important: the rotation loss should be calculated only for regions
            # of interest that match with a ground truth object instance.
            # Note that the helper function, IOUselection, may be used for 
            # identifying the predicted regions of interest with acceptable IOU 
            # with the ground truth bounding boxes.
            # If no ROIs result from the selection, don't compute the loss_R
            
            # Replace "pass" statement with your code

            #在这里你需要实现 PoseCNN 的训练过程：
            #TODO 15:使用特征提取器提取图像特征
            feat1, feat2 = 

            #TODO 16:使用分割分支进行物体分割，并计算分割损失
            probab, segmk, d_bbx =  # 填充分割分支的前向传播
            loss_dict["loss_segmentation"] =  # 填充交叉熵损失计算

            trans = self.TranslationBranch(feat1, feat2)
            mae_loss = nn.L1Loss()
            loss_dict["loss_centermap"] = mae_loss(trans, input_dict['centermaps'])

            gt_bbx = gt_bbx.to(torch.cuda.FloatTensor())

            filter_bbx_R = IOUselection(d_bbx, gt_bbx, self.iou_threshold)

            if filter_bbx_R.shape[0] != 0:
                quater = self.RotationBranch(feat1, feat2, gt_bbx[:, :5])  # TODO: 填充旋转分支的前向传播
                gt_R = self.gtRotation(filter_bbx_R, input_dict)  # 获取真实的旋转矩阵

                pred_R, label = self.estimateRotation(quater, filter_bbx_R)  # 估计旋转矩阵
                label = label.long()  # 转换标签为长整型
                loss_dict["loss_R"] = loss_Rotation(pred_R, gt_R, label, self.models_pcd)  # 计算旋转损失
            else:
                loss_dict["loss_R"] = 0  # 如果没有选择到区域，旋转损失为 0



            ######################################################################
            #                            END OF YOUR CODE                        #
            ######################################################################
            
            return loss_dict
        else:
            output_dict = None
            segmentation = None

            with torch.no_grad():
                ######################################################################
                # TODO: Implement PoseCNN's forward pass for inference.              #
                ######################################################################
                # 在这里，你需要实现 PoseCNN 的推理过程：
                # 1) 使用特征提取器提取输入图像的特征 `feat1` 和 `feat2`。
                # 2) 使用分割分支得到每个物体的分割结果 `segmentation` 和边界框 `bb_xs`。
                # 3) 使用平移分支预测物体的平移 `trans_i`。
                # 4) 使用旋转分支预测物体的旋转四元数 `quater`。
                # 5) 使用 `HoughVoting` 来预测物体中心点 `pred_centers` 和深度 `pred_depths`。
                # 6) 最后使用 `generate_pose` 来生成最终的位姿。

                # TODO 17: 填充特征提取过程，提取图像特征
                feat1, feat2 = 

                # TODO 18: 填充分割分支的前向传播，得到分割结果和边界框
                trans_i =

                # TODO 19: 将边界框转换为正确的类型，以便后续计算
                bb_xs =

   
                # TODO 20: 填充旋转分支的前向传播，得到旋转四元数             
                quater =

                # TODO 21: 使用 `estimateRotation` 来估算物体的旋转矩阵         
                pred_R, _ = 

                # TODO 22: 使用 `HoughVoting` 预测物体中心点和深度
                pred_centers, pred_depths =


                bb_xs = bb_xs.to(torch.cuda.LongTensor())


                output_dict = self.generate_pose(pred_R, pred_centers, pred_depths, bb_xs)


                ######################################################################
                #                            END OF YOUR CODE                        #
                ######################################################################

            return output_dict, segmentation
    
    def estimateTrans(self, translation_map, filter_bbx, pred_label):
        """
        计算每个边界框的平移预测。通过匹配类别标签，提取对应的平移信息，并计算每个类别的平均平移。
        """
        N_filter_bbx = filter_bbx.shape[0]  # 获取边界框数量
        pred_Ts = torch.zeros(N_filter_bbx, 3)  # 初始化平移预测张量

        # 遍历每个边界框，计算其平移
        for idx, bbx in enumerate(filter_bbx):
            batch_id = int(bbx[0].item())
            cls = int(bbx[5].item())
            trans_map = translation_map[batch_id, (cls-1) * 3 : cls * 3, :]
            label = (pred_label[batch_id] == cls).detach()
            pred_T = trans_map[:, label].mean(dim=1)
            pred_Ts[idx] = pred_T
        return pred_Ts

    def gtTrans(self, filter_bbx, input_dict):
        """
        提取每个边界框的真实平移信息。通过输入字典获取真实平移值。
        """
        N_filter_bbx = filter_bbx.shape[0]
        gt_Ts = torch.zeros(N_filter_bbx, 3)    # 初始化真实平移张量
        for idx, bbx in enumerate(filter_bbx):
            batch_id = int(bbx[0].item())
            cls = int(bbx[5].item())
            gt_Ts[idx] = input_dict['RTs'][batch_id][cls - 1][:3, [3]].T
        return gt_Ts 

    def getGTbbx(self, input_dict):
        """
        从输入字典中提取有效物体的边界框，过滤掉背景物体。
        """
        gt_bbx = []
        objs_id = input_dict['objs_id']
        device = objs_id.device
        #[x_min, y_min, 宽度, 高度]
        bbxes = input_dict['bbx']
        for batch_id in range(bbxes.shape[0]):
            for idx, obj_id in enumerate(objs_id[batch_id]):
                if obj_id.item() != 0:
                    # 该物体出现在图像中
                    bbx = bbxes[batch_id][idx]
                    gt_bbx.append([batch_id, bbx[0].item(), bbx[1].item(),
                                  bbx[0].item() + bbx[2].item(), bbx[1].item() + bbx[3].item(), obj_id.item()])
        return torch.tensor(gt_bbx).to(device=device, dtype=torch.int16)
        
    def estimateRotation(self, quaternion_map, filter_bbx):
        """
        quaternion_map: 一个张量，尺寸为 [batch_size, num_classes * 3, height, width]
        filter_bbx: 一个张量，尺寸为 N_filter_bbx * 6，包含 (batch_ids, x1, y1, x2, y2, cls)
        """
        N_filter_bbx = filter_bbx.shape[0]
        pred_Rs = torch.zeros(N_filter_bbx, 3, 3)
        label = []
        for idx, bbx in enumerate(filter_bbx):
            batch_id = int(bbx[0].item())
            cls = int(bbx[5].item())
            quaternion = quaternion_map[idx, (cls-1) * 4 : cls * 4]
            quaternion = nn.functional.normalize(quaternion, dim=0)
            pred_Rs[idx] = quaternion_to_matrix(quaternion)
            label.append(cls)
        label = torch.tensor(label)
        return pred_Rs, label

    def gtRotation(self, filter_bbx, input_dict):
        N_filter_bbx = filter_bbx.shape[0]
        gt_Rs = torch.zeros(N_filter_bbx, 3, 3)
        for idx, bbx in enumerate(filter_bbx):
            batch_id = int(bbx[0].item())
            cls = int(bbx[5].item())
            gt_Rs[idx] = input_dict['RTs'][batch_id][cls - 1][:3, :3]
        return gt_Rs 

    def generate_pose(self, pred_Rs, pred_centers, pred_depths, bbxs):
        """
        pred_Rs: 一个张量，尺寸为 [pred_bbx_size, 3, 3]，表示预测的旋转矩阵
        pred_centers: 尺寸为 [batch_size, num_classes, 2]，表示预测的物体中心点坐标
        pred_depths: 一个张量，尺寸为 [batch_size, num_classes]，表示预测的物体深度
        bbx: 一个张量，尺寸为 [pred_bbx_size, 6]，表示边界框信息，包含 (batch_ids, x1, y1, x2, y2, cls)
        """        
        output_dict = {}
        for idx, bbx in enumerate(bbxs):
            bs, _, _, _, _, obj_id = bbx
            R = pred_Rs[idx].numpy()
            center = pred_centers[bs, obj_id - 1].numpy()
            depth = pred_depths[bs, obj_id - 1].numpy()
            if (center**2).sum().item() != 0:
                T = np.linalg.inv(self.cam_intrinsic) @ np.array([center[0], center[1], 1]) * depth
                T = T[:, np.newaxis]
                if bs.item() not in output_dict:
                    output_dict[bs.item()] = {}
                output_dict[bs.item()][obj_id.item()] = np.vstack((np.hstack((R, T)), np.array([[0, 0, 0, 1]])))
        return output_dict


def eval(model, dataloader, device, alpha = 0.35):
    import cv2
    model.eval()# 设置模型为评估模式

    sample_idx = random.randint(0,len(dataloader.dataset)-1)
    #图像的可视化
    rgb = torch.tensor(dataloader.dataset[sample_idx]['rgb'][None, :]).to(device)
    inputdict = {'rgb': rgb}
    pose_dict, label = model(inputdict)
    poselist = []
    rgb =  (rgb[0].cpu().numpy().transpose(1, 2, 0) * 255).astype(np.uint8)
    # 可视化并返回结果
    return dataloader.dataset.visualizer.vis_oneview(
        ipt_im = rgb, 
        obj_pose_dict = pose_dict[0],
        alpha = alpha
        )
